// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iscdtojvosvwrncvvqhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY2R0b2p2b3N2d3JuY3Z2cWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTgxMzcsImV4cCI6MjA3MDQ3NDEzN30.dlMJqU0g7wJ21rJdIwhvq2MMbiIfYIShWvnNgQmW6P0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});